fixed the steam social button
sButtons/sbuttons pull request #1009
Opened 2020-10-30 17:38 UTC by KyleBreedlove

Fixed the Steam Social button that was not showing up.

Issue: 1000 "Login with Steam Social button is not visible"

2020-10-30 18:44 UTC, glebkema requested changes
Thanks for your contribution! Your code solves the problem, but your need to edit the `.less` files and compile them with the `npm run compile` command instead of editing the `.css` files directly.

Look for the detailed instructions here:
https://github.com/sButtons/sbuttons/blob/master/CONTRIBUTING.md#instructions

2020-10-30 18:45 UTC, glebkema requested changes
< please remove this duplicate comment >

2020-10-30 19:08 UTC, KyleBreedlove commented
My bad, completely glossed over that part. Should I create a new request and do it the correct way?

2020-10-30 19:22 UTC, glebkema commented
The best way is to add a new commit to this pull request.

2020-11-02 08:11 UTC, shahednasser requested changes
Can you please remove all changes in `package-lock.json` and `package.json`?

2020-11-03 11:31 UTC, shahednasser requested changes

2020-11-03 11:31 UTC, shahednasser commented on README.md
> +[![All Contributors](https://img.shields.io/badge/all_contributors-162-orange.svg?style=flat-square)](./CONTRIBUTORS.md)
remove this change

2020-11-05 08:26 UTC, merged

2020-11-05 08:26 UTC, shahednasser commented
Great work @KyleBreedlove thank you!

@all-contributors please add @KyleBreedlove for code and bug