Added Animated Gradient Border Button
sButtons/sbuttons pull request #1071
Opened 2020-10-31 18:29 UTC by parresh77

Issue: #418

2020-10-31 21:39 UTC, shahednasser requested changes
I like your work but I have a question: why are there no rounded and block button? I get it might not work for rounded but please at least make a normal sized button and a block button.

2020-10-31 21:39 UTC, shahednasser commented on assets/js/buttons-examples.js
> +          label: "Animated Gradient Border",
remove the animated from the label and place it then at the correct alphabetical order.

2020-10-31 21:39 UTC, shahednasser commented on src/components/animated/_gradient-border.less
> +@import "https://fonts.googleapis.com/css?family=Raleway:200";
please remove font as it is not necessary for the design of the button

2020-11-01 19:07 UTC, parresh77 commented
@shahednasser I've made all the requested changes. I've also changed the dimensions of the button to make it look good collectively in both basic and block size.

2020-11-02 08:06 UTC, shahednasser requested changes

2020-11-02 08:06 UTC, shahednasser commented on assets/js/buttons-examples.js
> +          // shouldHaveBlockType: false,
Remove this line

2020-11-02 18:53 UTC, parresh77 commented
@shahednasser Removed the comment.

2020-11-03 11:42 UTC, merged

2020-11-03 11:42 UTC, shahednasser commented
Great work thank you!

@all-contributors please add @parresh77 for code