Fix for Inconsistent loading button labels #1075
sButtons/sbuttons pull request #1098
Opened 2020-11-02 13:17 UTC by jlieow

Inside "buttons-examples.js", updated text for Loading which is a child of Animated Buttons.

Button animation with loading right 

Issue: Fix for Inconsistent loading button labels #1075

Fixed labels for buttons with loading animation. Button with loading animation on left side are labeled "loading left", and those on the right side are labeled "loading right".

2020-11-03 11:31 UTC, shahednasser requested changes
All looks great but I want you to do something additional for me: I think it will look better if the left buttons where together and the right buttons where after. You just need to rearrange them.

2020-11-03 14:41 UTC, jlieow commented
> All looks great but I want you to do something additional for me: I think it will look better if the left buttons where together and the right buttons where after. You just need to rearrange them.

Sure. I will keep the colors as they are in their current positions and make the buttons on the top left buttons and buttons on the bottom right buttons.

2020-11-04 12:16 UTC, shahednasser requested changes
Great but now there are duplicate buttons so can you please remove all duplicate buttons?

2020-11-04 13:19 UTC, jlieow commented
My mistake, I didn't realise.

2020-11-04 13:22 UTC, jlieow commented
I have removed duplicate buttons.

I have also rearranged buttons, it looks better with left buttons on left half and right buttons on right half.

2020-11-05 09:09 UTC, merged

2020-11-05 09:09 UTC, shahednasser commented
Awesome work thank you!

@all-contributors please add @jlieow for code