Added title to the download and github icons like darkMode button
sButtons/sbuttons pull request #1126
Opened 2020-11-05 13:51 UTC by Hrshk15

Earlier when user hovered over the download and github buttons nothing used to show in order to tell user what these buttons will do like the darkmode button used to tell.

Now I have added the titles to download and github buttons, when user hover over download button it shows - "download sbuttons.min.css" and when user hovers over github button it shows "sbuttons repo".
Issue:

2020-11-06 07:28 UTC, shahednasser requested changes
Great @Hrshk15 but this change will only be seen in the homepage. Can you also add it in the documentation and examples pages?

2020-11-06 07:28 UTC, shahednasser commented on index.html
> +            <i class="fab fa-github" title="sbuttons repo"></i>
Change sbuttons to "sButtons"

2020-11-06 10:24 UTC, Hrshk15 commented
@shahednasser  Done with the required changes

2020-11-06 16:09 UTC, Hrshk15 reviewed
checked

2020-11-09 11:06 UTC, shahednasser requested changes
Great but please remove all changes in `dist/sbuttons.css` as they are unnecessary

2020-11-15 17:24 UTC, Hrshk15 commented
> Great but please remove all changes in `dist/sbuttons.css` as they are unnecessary

I am not able to get it, I have not even edited anything in dist/sbuttons.css .

2020-11-18 18:12 UTC, shahednasser commented
@Hrshk15 the easiest way is to just copy the content of the file in the repo then committing the changes.

2020-11-27 08:22 UTC, shahednasser commented
@Hrshk15 any update on this?

2020-12-05 00:15 UTC, closed without merging