Toggle Button Documentation
sButtons/sbuttons pull request #1157
Opened 2020-11-19 09:16 UTC by VinayakChopra

This pull request adds the use of the toggle button as checkboxes and radio buttons into the documentation page as well as documents the same in the readme.md file.

Issue: Add documentation about toggle button #983

2020-11-20 07:17 UTC, shahednasser requested changes
Thank you for your work @VinayakChopra . I'd like to fix something about the documentation which is to indicate that the "toggle-off-btn" and "toggle-on-btn" are not necessary for checkboxes and radio buttons, they are just necessary for normal buttons. For checkboxes and radio buttons, it just depends on whether they're checked or not. Make sure to explain that in the documentation. 

I have also added some changes that should be done below. Please make sure that the changes indicated in the website should be made in the README as well.

2020-11-20 07:17 UTC, shahednasser commented on documentation.html
> +            The <code>toggle-btn</code> class along with <code>toggle-off-btn</code> / <code>toggle-on-btn</code> state class enables you to have a toggle button.Apart from its basic use, it can be u
Please fix the spacing in words like "radiobuttons"

2020-11-20 07:17 UTC, shahednasser commented on documentation.html
> +              Adding the <code>toggle-btn toggle-off-btn</code> class to your checkbox inputs converts them to toggle buttons.For example:
`toggle-off-btn` is not required for checkboxes and radio buttons. Only for normal buttons

2020-11-20 07:17 UTC, shahednasser commented on README.md
> +    -[Toggle Button as Checkboxes](#toggle-button-as-checkboxes)
There's a problem in the indentation please fix it (make sure it's similar to the previous menu items)

2020-11-20 07:17 UTC, shahednasser commented on documentation.html
> +              <input type="checkbox" id="1" class="sbtn toggle-btn toggle-off-btn" />
The example should just be one checkbox with the code block for it. No need to include a full example (same thing for radio buttons) Also don't include a label as it is not necessary

2020-11-20 07:17 UTC, shahednasser commented on documentation.html
> +              Adding the <code>toggle-btn toggle-off-btn</code> class to your radio inputs converts them to toggle buttons.For example:
Add a space before "For example"

2020-11-23 05:01 UTC, VinayakChopra commented
Hi @shahednasser thanks for reviewing the work, I have made the said changes in the new commit.

2020-11-23 14:07 UTC, merged

2020-11-23 14:07 UTC, shahednasser commented
Great thank you!

@all-contributors please add @VinayakChopra for documentation