Add Dark Mode Support for Expanding Border, Snake Border, and Star Icon
sButtons/sbuttons pull request #1163
Opened 2020-11-20 22:02 UTC by TomWBush

Issue: #1014 

Please see the demo below :)

![expanding](https://user-images.githubusercontent.com/34357020/99854025-0e2bdb80-2b52-11eb-8f87-182041674304.gif)
![snake](https://user-images.githubusercontent.com/34357020/99854027-0ff59f00-2b52-11eb-9384-e9321fb2c86c.gif)
<img width="437" alt="Screen Shot 2020-11-20 at 4 59 01 PM" src="https://user-images.githubusercontent.com/34357020/99854031-11bf6280-2b52-11eb-8786-2f1ca80293d8.png">

2020-11-21 18:04 UTC, shahednasser requested changes
Thank you @TomWBush your work is great as always, but I have just small changes below to make the code a little better.

2020-11-21 18:04 UTC, shahednasser commented on src/components/animated/_expanding.less
> +      border: 0.2rem solid #fff;
Instead of repeating this line, change the selector from `&:before` to `&, &:before`

2020-11-21 18:04 UTC, shahednasser commented on src/components/animated/_expanding.less
> +    border: 0.2rem solid #fff;
Remove this line after changing the selector

2020-11-21 18:04 UTC, shahednasser commented on src/components/animated/_snake.less
> +      &:before {
Change the selector to `&:before, &:after` and remove the rule for `&:after` below.

2020-11-22 02:02 UTC, TomWBush commented
Thanks for the suggestions. I have made the corresponding changes.

2020-11-23 11:11 UTC, merged

2020-11-23 11:11 UTC, shahednasser commented
Thank you @TomWBush !