Adding rainbow button css
sButtons/sbuttons pull request #1313
Opened 2021-02-19 13:06 UTC by princeo1

In this pull request I added a button type  css for button which have rainbow animation

Issue:Add animated class to animated buttons

2021-02-19 13:19 UTC, princeo1 commented
> In this pull request I added a button type css for button which have rainbow animation
> 
> Issue:Add animated class to animated buttons

Please take care that the following should be the HTML code

<a href="#" class="rainbow-btn" alt="Button"></a>

2021-02-19 13:29 UTC, shahednasser requested changes
Hello @princeo1 thank you for your work. You don't need to create a new file, you need to make changes in `src/components/animated/_rainbow.less` and add an animated class that does what the button does on hover. Please remove the file you added and just make changes in the file specified

2021-02-21 15:53 UTC, shahednasser requested changes
You still need to run `npm run compile` and commit the changes

2021-02-21 15:53 UTC, shahednasser commented on src/sbuttons.less
> +@import "components/_rainbow.less";
Please remove this line

2021-02-21 21:51 UTC, shahednasser commented
@princeo1 Please run `npm run compile` and commit the changes

2021-03-01 16:03 UTC, shahednasser commented
Hi @princeo1 any update on this?

2021-03-05 20:19 UTC, closed without merging