Added dropdown menu in home page
sButtons/sbuttons pull request #1327
Opened 2021-02-24 12:38 UTC by dsnehasish74

Issue:

2021-02-25 09:28 UTC, shahednasser requested changes
Great work @dsnehasish74 I just need you to make the following changes:

1. can you move the arrow next to the logo and add "Menu" as a title to it as well? That way it wouldn't be confusing.
2. Change the color of the dropdown divider to #42668a
3. When the dropdown is opened on a small device and the screen is enlarged, the dropdown is still visible. it should close.

2021-02-25 09:28 UTC, shahednasser commented on index.html
Remove this additional line

2021-02-25 10:37 UTC, dsnehasish74 commented
Ok I am doing it

2021-02-26 21:18 UTC, shahednasser requested changes

2021-02-26 21:18 UTC, shahednasser commented on assets/js/index.js
> +  if ($(this).width() < 767) {
This should be greater than 768

2021-02-26 21:18 UTC, shahednasser commented on assets/css/header.css
> +  background-color: #42668a;
this should be the color of the border not background

2021-02-28 11:13 UTC, shahednasser commented on assets/js/index.js
> +  if ($(this).width() < 768) {
Should be greater not less

2021-02-28 16:53 UTC, merged

2021-02-28 16:53 UTC, shahednasser commented
Great thank you!