Website readme update
sButtons/sbuttons pull request #1358
Opened 2021-03-19 21:20 UTC by Caleb335

Issue:

2021-03-20 11:23 UTC, shahednasser requested changes
Great work but can you update the table of content as well?

2021-03-20 11:23 UTC, shahednasser commented on README.md
> +Check out `_variables.less` for the full list of variables.
Add a link to _variables.less here

2021-03-20 14:45 UTC, Caleb335 commented
Alright, I'd get to it.

2021-03-22 09:21 UTC, Caleb335 commented
I've made the changes you requested @shahednasser.

Kindly review

2021-03-22 11:56 UTC, merged

2021-03-22 11:56 UTC, shahednasser commented
Great work as always thank you!