Fix Documentation sidebar links
sButtons/sbuttons pull request #1364
Opened 2021-03-22 23:47 UTC by snapecode

Adjusted the sidebar Link Levels and added a missing modify colors link.

2021-03-23 08:16 UTC, shahednasser commented
Thank you for your work. It seems there's an additional problem in the `SidebarLink component` here:

https://github.com/sButtons/sbuttons/blob/ab79052fd3c0b7e9fcbbaa02fa55ef0843f4f3a0/website/src/components/SidebarLink.js#L31-L35

can you please change `ml-${level * 3}` to `ml-${level ? level + 3 : 0}` ? I think it would be more fitting.

Also, please remove all changes in package-lock.json

2021-03-23 16:17 UTC, snapecode commented
Hi @shahednasser, I made the change to sidebar Link and reverted package-lock. Is the pull request correct? I feel like I may have merged an old branch. Please keep recommending little changes so I can practice these push and pulls.
The sidebar does still seem a little out of place and not perfectly aligned, and the footer pushing in from the bottom. What do you think?

2021-03-24 08:05 UTC, shahednasser requested changes
It seems that you reverted the changes you did as well with the sidebarlink levels, that's why it still seems not aligned correctly. Please add the changes you added before to the sidebarlink levels

2021-03-25 06:36 UTC, shahednasser requested changes

2021-03-25 06:36 UTC, shahednasser commented on website/src/pages/Documentation/index.js
> +                    <SidebarLink to="#only-icon" text="Only Icon" level={4} />
Only icon, icon-left and icon-right should be level 2

2021-03-25 06:36 UTC, shahednasser commented on website/src/pages/Documentation/index.js
> +                    <SidebarLink to="#toggle-button-radio" text="Toggle Button as Radio Buttons" level={4} />
toggle-button-checkbox and toggle-button-radio should be level 2

2021-03-25 06:36 UTC, shahednasser commented on website/src/pages/Documentation/index.js
> +                    <SidebarLink to="#dark-mode-class" text="Using dark-mode Class" level={4} />
dark-mode-class and dark-mode-attribute should be level 2

2021-03-30 11:29 UTC, shahednasser commented on website/src/components/SidebarLink.js
> +            className={`block ${active ? 'border-red-600' : ''} sidebar-item lg:w-max text-lg border-b-2 border-transparent hover:border-red-600 dark:text-white ml-${level ? level + 3 : 0}`}>{text}</
sorry for the delay @snapecode but can you please change this to `level + 2`?

2021-04-01 11:07 UTC, merged

2021-04-01 11:07 UTC, shahednasser commented
Great work thank you!

@all-contributors please add @snapecode for code and bug