Added documentation for animated buttons
sButtons/sbuttons pull request #1374
Opened 2021-04-12 06:00 UTC by snapecode

Added documentation for animated buttons to README and Documentation page

2021-04-12 10:59 UTC, shahednasser requested changes
Thank you for your work @snapecode please find my comments below

2021-04-12 10:59 UTC, shahednasser commented on README.md
> +<button class="sbtn atom-btn blue-btn">Animated Button</button>
you should add `animated` to the list of classes in the example.

2021-04-12 10:59 UTC, shahednasser commented on website/src/pages/Documentation/index.js
> +                                <Code code={`<button class="sbtn atom-btn blue-btn">Animated Button</button>`} language="html" />
The class `animated` should be added to this code + the example below it

2021-04-12 23:13 UTC, snapecode commented
Got the animated classes in, how is the description in the readme? could it use more info on using the mixins?

2021-04-13 07:48 UTC, merged

2021-04-13 07:48 UTC, shahednasser commented
Great work thank you!

@all-contributors please add @snapecode for documentation