PayPal button added
sButtons/sbuttons pull request #1508
Opened 2021-10-05 10:22 UTC by mrSidSat

Issue: #1501 

paypal button is added .

2021-10-05 12:01 UTC, shahednasser requested changes
Hi @mrSidSat thank you for your work. I have a few comments:

1. there are some unnecessary changes in sbuttons.css. Please make sure you're not manually making any edits.
2. There are a lot of changes in `buttons.json`, seems to be due to your editor's formatting. this can be a big issue to other contributors as this change will propagate.
3. There are changes in `website/package-lock.json

Here's what you need to do:

1. Fix the comments I added in `_paypal.less`.
2. run `npm run compile` and `npm run clean-css`.
3. revert `buttons.json` to the original format and just add your button.
4. remove all changes in `website/package.json`.
5. commit your changes.

2021-10-05 12:43 UTC, mrSidSat commented
Thanks for the review , would do the changes ASAP

2021-10-05 16:24 UTC, mrSidSat commented
All the required changes are made

2021-10-05 18:56 UTC, shahednasser requested changes
All looking great @mrSidSat but there's one problem I just noticed which is for rounded buttons the icon is now too close to the corner. So, set `right: 5px;` for rounded buttons only.

Don't forget to run `npm run compile` and `npm run clean-css` before committing the changes.

2021-10-06 03:51 UTC, mrSidSat commented
The changes are made...

2021-10-06 17:28 UTC, shahednasser commented on dist/sbuttons.css
> +  transform: translate3d(0, 200%, 0);
I have noticed @RajMhatre20 as I have seen the same issue in other PRs, thank you for pointing it out as well!

2021-10-06 17:38 UTC, merged