Adding Rotate Anticlockwise button
sButtons/sbuttons pull request #1567
Opened 2021-11-03 04:51 UTC by nisarga-kh

Issue:
This PR is to add a new type of button called Rotate anticlockwise button. This button rotates in anticlockwise direction when hovered.

2021-11-03 10:52 UTC, shahednasser requested changes
Thank you @nisarga-kh but you need to make the following changes:

1. import `_rotate-anticlockwise.less` in `animated.less`
2. Run `npm run build`

After you do that please commit the changes so that we can see them on the website

2021-11-03 10:52 UTC, shahednasser commented on website/src/data/buttons.json
> +
Remove these empty lines

2021-11-03 17:27 UTC, nisarga-kh commented
@shahednasser Have done the necessary modifications and have committed. Please do review once

2021-11-05 13:42 UTC, shahednasser requested changes
Thank you @nisarga-kh for making the changes but the problem with this is that you're using in the animation the `top` and `left` attributes, but this button isn't absolute and it shouldn't be.

I suggest you use translate in the animation instead.

2021-11-20 00:28 UTC, closed without merging