added neumorphic button styles
sButtons/sbuttons pull request #293
Opened 2020-09-29 02:57 UTC by justDOindev

added neumorphic button styles in neumorphic.less. I have not added any examples to the website at this time.

Issue:

2020-09-29 11:04 UTC, shahednasser commented
Hi @justDOindev thank you for your work. Can you please add some examples so I can review them?

2020-10-03 14:19 UTC, Summer-source commented
I would like to work on this!

2020-10-04 15:57 UTC, justDOindev commented
ok will do

2020-10-04 16:42 UTC, justDOindev commented
so I am not very experienced at GitHub yet so not sure how to do this, I updated my local branch and had to make some changes to my code to make it work again, should I create a new pr to replace this one or add examples to this pr then make a new pr with the fixes? this pr does not have _neumorphic.less in special folder and uses .btn-rounded instead of .rounded-btn

2020-10-04 17:59 UTC, justDOindev commented
updated everything, Here are some examples

![lightneu](https://user-images.githubusercontent.com/44042682/95023161-087d4380-0641-11eb-8e3b-9fab506cc9d8.png)
![darkneu](https://user-images.githubusercontent.com/44042682/95023170-0c10ca80-0641-11eb-8621-8d9aa465b838.png)

2020-10-04 18:48 UTC, shahednasser requested changes
Hi @justDOindev you still need to add the button to `assets/js/buttons-examples.js` to see it on the website.

2020-10-04 19:46 UTC, justDOindev commented
My bad, Will do. Thank you for your patience

2020-10-05 08:04 UTC, shahednasser requested changes
Please remove the background color you added and just keep the styling is it is (don't make any changes to `assets/css/index.css`).

2020-10-05 08:04 UTC, shahednasser commented on assets/js/buttons-examples.js
> +          label: "neumorphic",
Place it in the correct alphabetical order under `special` and capitalize the first letter (same for the light and dark)

2020-10-05 19:10 UTC, justDOindev commented
Ok will do

2020-10-06 12:22 UTC, shahednasser commented
Shouldn't the dark buttons have dark background? The button itself not the entire background? Can you assign the color you used previously for the background as the background color of dark buttons?

2020-10-06 12:22 UTC, shahednasser commented
If not then please instead of two sections make it one section.

2020-10-06 12:32 UTC, justDOindev commented
ok

2020-10-11 00:33 UTC, justDOindev commented
changed the shadows slightly to work on all backgrounds. the effect pops best on mid-range shades but looks good across the board.

![grayneu](https://user-images.githubusercontent.com/44042682/95667693-180ff700-0b2f-11eb-8182-de55b9cc4918.png)
![redneu](https://user-images.githubusercontent.com/44042682/95667695-1ba37e00-0b2f-11eb-96b7-3ba86ccbfdd3.png)
![lightgrayneu](https://user-images.githubusercontent.com/44042682/95667699-1f370500-0b2f-11eb-9336-2f1f1123a3d5.png)

2020-10-11 13:47 UTC, justDOindev commented
Now there is only one button variation instead of the light/dark variations

2020-10-12 17:05 UTC, merged

2020-10-12 17:05 UTC, shahednasser commented
Awesome work thank you!

@all-contributors please add @justDOindev for code