Moved the variables to new file, and edited README.md
sButtons/sbuttons pull request #441
Opened 2020-10-01 11:50 UTC by annettomcy

Issue:

2020-10-01 12:01 UTC, shahednasser requested changes
Can you run `npm run compile` after you finish to see if anything in the website is affected by this change?

2020-10-01 12:01 UTC, shahednasser commented on README.md
> +@import '/path/to/_variables.less';
Please don't change this.

2020-10-01 12:01 UTC, shahednasser commented on README.md
> +To modify button colors, import `src/_variables.less` in your Less file, then make changes to the variables after the import.
Please don't change this

2020-10-01 12:04 UTC, annettomcy commented on README.md
> +@import '/path/to/_variables.less';
Okay, will revert that

2020-10-01 12:04 UTC, annettomcy commented on README.md
> +To modify button colors, import `src/_variables.less` in your Less file, then make changes to the variables after the import.
Okay will revert that

2020-10-01 12:05 UTC, annettomcy commented
Okay will run npm run compile after I finish.

2020-10-01 17:57 UTC, shahednasser commented
@annettomcy did you run `npm run compile`? where there any changes?

2020-10-03 11:28 UTC, shahednasser commented
Hi @annettomcy this is an urgent issue (as it has priority high) and other PRs are dependant on it. Can you finish this by today? If not I need to reassign it quickly.

2020-10-04 04:43 UTC, annettomcy commented
Yes I ran npm run compile and the website worked fine, are there any more changes?

2020-10-04 10:54 UTC, shahednasser commented
I cloned your repository and ran `npm run compile` and there were a lot of changes. Can you commit the changes you find after running it?

2020-10-06 06:10 UTC, annettomcy commented
Hey are the changes visible now

2020-10-06 06:11 UTC, annettomcy commented
Hey are the changes visible

2020-10-06 12:18 UTC, shahednasser requested changes

2020-10-06 12:18 UTC, shahednasser commented on package.json
> +    "prettier": "^2.1.2",
Please remove this change

2020-10-07 18:24 UTC, shahednasser commented
Closing this as you took a long time on a high priority issue. Thank you.

2020-10-07 18:24 UTC, closed without merging