Refactored appstore
sButtons/sbuttons pull request #679
Opened 2020-10-05 18:45 UTC by SamD97

Issue: Common in properties in `&.appstore` and `&.playstore`

Solution: Common properties were moved out to the parent.

2020-10-05 19:55 UTC, shahednasser commented
Regarding the comment you mentioned I didn't notice the different left attributes, so put those with the content instead of in the parent element.

2020-10-05 20:06 UTC, SamD97 commented
> Regarding the comment you mentioned I didn't notice the different left attributes, so put those with the content instead of in the parent element.

I am slightly confused, you meant to say "I did notice the different `left` attributes" right?
https://github.com/sButtons/sbuttons/blob/82dfc98c10f6020f1797b537b5cba436abd7333b/src/components/icon/_appstore.less#L46
https://github.com/sButtons/sbuttons/blob/82dfc98c10f6020f1797b537b5cba436abd7333b/src/components/icon/_appstore.less#L69

Anyways I am assuming that's what you meant based on the latter part of your reply and undo that change.

2020-10-06 06:39 UTC, shahednasser requested changes
So I checked the current website and apparently the different left attributes (100px and 87px) is only applied when the button is block, else it's always 50px so can we refactor the code to portray that? Change the 87px to 102px as a fix to the original button's design.

Also for the `.appstore-btn` when it's a block button please change the padding left to 30px as a fix to the original button.

2020-10-06 08:05 UTC, SamD97 commented on dist/sbuttons.css
> +  padding-left: 30px;
The `padding-left: 30px` only affects `.block-btn` because of line 31

2020-10-06 08:07 UTC, shahednasser requested changes

2020-10-06 08:07 UTC, shahednasser commented on src/components/icon/_appstore.less
> +  padding-left: 30px;
This change should only be applied to `applestore.block-btn` not all. Please fix this and change the default back to 60px

2020-10-06 08:07 UTC, SamD97 commented on src/components/icon/_appstore.less
> +  padding-left: 30px;
The `padding-left: 30px` only affects `.block-btn` because of line 31 hence for other buttons it is `50px`

2020-10-06 08:47 UTC, merged

2020-10-06 08:47 UTC, shahednasser commented
Great work thank you!

2020-10-06 08:48 UTC, SamD97 commented
Thank you for all the help and feedback :+1: