fix overlaying scrollbar
sButtons/sbuttons pull request #719
Opened 2020-10-07 17:03 UTC by Caleb335

Issue: #564 

@shahednasser 

At first, when I launched the website on my PC, The links were not overlapping the footer, that was because the content wasn't much then, so I went on to add additional button examples in the `button-examples.js` file so I'd be able to see the error.

I fixed this error by adding a fixed width to the submenu links of all the button examples and allowing them to overflow, thus, the scrollbar you see..

Kindly check the GIF below to see it in action.
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/48127194/95363304-34115f80-08c7-11eb-8017-0789a804a350.gif)

2020-10-07 18:09 UTC, shahednasser requested changes
That's a nice idea but on certain screen widths the buttons still overlap with the footer (for example when the height is less than 600px). So can you still make the sidebar hide behind the footer? This is just a temporary change so I don't want you to work on a complex fix.

Also, can you make all these changes (the changes you made and making the sidebar behind the footer) only on devices with width >= 768px? As on small devices it is unnecessary

2020-10-07 18:45 UTC, Caleb335 commented
> That's a nice idea but on certain screen widths the buttons still overlap with the footer (for example when the height is less than 600px). So can you still make the sidebar hide behind the footer? This is just a temporary change so I don't want you to work on a complex fix.

Okay, I'd work on that

> Also, can you make all these changes (the changes you made and making the sidebar behind the footer) only on devices with width >= 768px? As on small devices it is unnecessary

Oh! I noticed that also when I was viewing the preview

2020-10-07 20:40 UTC, Caleb335 commented
@shahednasser I've added the requested change.

Kindly review

2020-10-08 10:59 UTC, shahednasser requested changes
Looks great but these changes are still being applied to small devices. Can you add the media query to avoid that? All changes made should be in the media query.

2020-10-08 12:01 UTC, Caleb335 commented
> Looks great but these changes are still being applied to small devices. Can you add the media query to avoid that? All changes made should be in the media query.

All done now.

Kindly review, Thanks

2020-10-08 17:47 UTC, shahednasser requested changes
I just realized that the links are now not clickable, so can you change the z-index of sidebar to 0 and add the following CSS rules to footer:

```
z-index: 2;
position: relative;
```

2020-10-08 22:12 UTC, Caleb335 commented
@shahednasser, I've made changes to the files you requested.

The links are clickable now.

Please review

2020-10-09 07:59 UTC, merged

2020-10-09 07:59 UTC, shahednasser commented
Great thank you!

@all-contributors please add @Caleb335 for bug