Added western theme buttons to animated
sButtons/sbuttons pull request #767
Opened 2020-10-09 23:43 UTC by laurachristensen1214

I added a Button Idea earlier today for leather-looking buttons. I named them "Western themed" and added them to the existing animated buttons.

Issue:

2020-10-10 08:52 UTC, shahednasser requested changes
It seems you have created 5 button types? I'm honestly not sure as I can't see the buttons yet. Please make the fixes below to see whether we need the buttons or not and we can proceed afterwards.

2020-10-10 08:52 UTC, shahednasser commented on src/components/animated/_western.less
> +    background: lighten(@charcoal, 3%);
You are using `@charcoal` but the variable is not defined

2020-10-10 08:52 UTC, shahednasser commented on assets/js/buttons-examples.js
> +    "denim-btn",
Why did you add the buttons here? These buttons are just different colors to be used for all button types. Please add them in the `buttons` variable instead under "Special"

2020-10-10 08:52 UTC, shahednasser commented on src/components/animated/_western.less
> +.denim-btn:hover {
nest this inside `.denim-btn`

2020-10-10 08:52 UTC, shahednasser commented on src/components/animated/_western.less
> +.choco-btn:hover {
nest this inside `.choco-btn`

2020-10-10 08:52 UTC, shahednasser commented on src/components/animated/_western.less
> +.charcoal-btn:hover {
nest this inside `.charcoal-btn`

2020-10-10 08:52 UTC, shahednasser commented on src/components/animated/_western.less
> +.sand-btn:hover {
nest this inside `.sand-btn`

2020-10-19 18:05 UTC, closed without merging

2020-10-23 19:49 UTC, laurachristensen1214 commented
Hi, @shahednasser I am sorry for the delay. This is something I am doing when I have free time in my work schedule, so I needed to put it on the back burner for a couple weeks. I have made the revisions you suggested and would really like to submit the updated pull request if possible?

2020-10-23 19:50 UTC, shahednasser commented
Sure @laurachristensen1214 please submit a new PR with your work.