Shine Button Effects in Shine.less
sButtons/sbuttons pull request #814
Opened 2020-10-15 09:14 UTC by hussein-hub

Issue:

2020-10-15 17:52 UTC, shahednasser requested changes
It looks much better! I just have two comments below. Also please remove all the commented out code.

2020-10-15 17:52 UTC, shahednasser commented on src/components/animated/_shine.less
> +  s &:active {
why is there an s here?

2020-10-15 17:52 UTC, shahednasser commented on src/components/animated/_shine.less
> +  &:hover {
nest in `.shine-btn` above

2020-10-16 12:12 UTC, hussein-hub commented
Will do the mentioned changes by today

On Thu, 15 Oct 2020, 11:22 pm Shahed Nasser, <notifications@github.com>
wrote:

> *@shahednasser* requested changes on this pull request.
>
> It looks much better! I just have two comments below. Also please remove
> all the commented out code.
> ------------------------------
>
> In src/components/animated/_shine.less
> <https://github.com/sButtons/sbuttons/pull/814#discussion_r505730282>:
>
> > @@ -46,4 +113,17 @@
>    &.orange-btn:active {
>      .bc(@darkOrange);
>    }
> +  s &:active {
>
> why is there an s here?
> ------------------------------
>
> In src/components/animated/_shine.less
> <https://github.com/sButtons/sbuttons/pull/814#discussion_r505730613>:
>
> > @@ -46,4 +113,17 @@
>    &.orange-btn:active {
>      .bc(@darkOrange);
>    }
> +  s &:active {
> +    &:after {
> +      opacity: 0;
> +    }
> +  }
> +}
> +.shine-btn {
> +  &:hover {
>
> nest in .shine-btn above
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sButtons/sbuttons/pull/814#pullrequestreview-509628171>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLYPGXNN2FT3WLUMSPXERTSK4ZGBANCNFSM4SRWX2UQ>
> .
>

2020-10-16 16:16 UTC, merged

2020-10-16 16:17 UTC, shahednasser commented
Great thank you!

@all-contributors please add @hussein-hub for code