Gradient
sButtons/sbuttons pull request #821
Opened 2020-10-15 18:01 UTC by Charu271

Issue:

2020-10-15 18:12 UTC, shahednasser requested changes
Please do the changes in the review and run `npm run compile` then commit the changes.

2020-10-15 18:12 UTC, shahednasser commented on src/_variables.less
> +@gradientPink: #e60550;
See the "Begin variables IN styles/_key.less" and "END VARIABLES IN styles/_key.less"? Move your variables from in between those comments and add before your variables similar comments before and after them but change _key.less to _gradient.less

2020-10-15 18:44 UTC, Charu271 commented
Mam, I am not able to push changes to this pull request. Shall I make a new pull request?

2020-10-15 19:33 UTC, merged

2020-10-15 19:33 UTC, shahednasser commented
Thank you!

@all-contributors please add @Charu271 for code

2020-10-15 19:35 UTC, Charu271 commented
Thanks mam. Can u please add a label of hacktober fest accepted

On Fri, 16 Oct 2020, 1:04 am allcontributors[bot], <notifications@github.com>
wrote:

> @shahednasser <https://github.com/shahednasser>
>
> I've put up a pull request <https://github.com/sButtons/sbuttons/pull/822>
> to add @Charu271 <https://github.com/Charu271>! 🎉
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sButtons/sbuttons/pull/821#issuecomment-709546076>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLEY7DAVYMZMLJMTR5MT4LSK5FDPANCNFSM4SSKCPEQ>
> .
>

2020-10-16 05:41 UTC, shahednasser commented
Hi @Charu271 don't worry, this repository has the "hacktoberfest" topic so all merged pull requests are accepted.

2020-10-16 05:45 UTC, Charu271 commented
Okay
Thank you mam

On Fri, 16 Oct 2020, 11:11 am Shahed Nasser, <notifications@github.com>
wrote:

> Hi @Charu271 <https://github.com/Charu271> don't worry, this repository
> has the "hacktoberfest" topic so all merged pull requests are accepted.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sButtons/sbuttons/pull/821#issuecomment-709804678>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLEY7CJI2W76KB4Y3MNTRLSK7MHXANCNFSM4SSKCPEQ>
> .
>