Removed the borders from splash button
sButtons/sbuttons pull request #896
Opened 2020-10-22 10:47 UTC by Hrshk15

As mentioned , I have removed the borders from the animated-splash-button.

Issue:
**How the button looked before \ How it will look**
![Screenshot (420)](https://user-images.githubusercontent.com/56513758/96861552-e299d080-1481-11eb-8b77-7e672d419c46.png)

2020-10-22 10:48 UTC, Hrshk15 commented
Done with the required changes.

2020-10-22 11:19 UTC, shahednasser requested changes
Great work but please remove on line 8 of `src/components/animated/_splash.less` the rule regarding border-color and any other rule regarding the border throughout the file that we don't need anymore.

2020-10-22 11:42 UTC, Hrshk15 commented
> Great work but please remove on line 8 of `src/components/animated/_splash.less` the rule regarding border-color and any other rule regarding the border throughout the file that we don't need anymore.

ok...

2020-10-22 11:50 UTC, Hrshk15 reviewed
Done with the changes.

2020-10-23 17:34 UTC, shahednasser requested changes
You still need to run `npm run compile` and commit the changes in `dist/sbuttons.css`

2020-10-24 01:55 UTC, Hrshk15 commented
O... got it.

2020-10-24 05:36 UTC, Hrshk15 commented
> You still need to run `npm run compile` and commit the changes in `dist/sbuttons.css`



> You still need to run `npm run compile` and commit the changes in `dist/sbuttons.css`

@shahednasser  I have  commited the changes into the new-branch....  can I create a new pull request .

2020-10-24 09:14 UTC, merged

2020-10-24 09:15 UTC, shahednasser commented
No need to create a new PR as commiting your code updates this PR.

Thank you for your work!

@all-contributors please add @Hrshk15 for code

2020-10-24 11:27 UTC, Hrshk15 commented
@shahednasser  Thanks for helping me out .