Added rainbow border button
sButtons/sbuttons pull request #910
Opened 2020-10-23 16:16 UTC by Soumi150

Fixes #882

2020-10-23 18:39 UTC, shahednasser reviewed
Thank you for your work @Soumi150 it looks great but on hover it does nothing. Can you fix it please?

2020-10-23 18:44 UTC, Soumi150 commented
I have added animation but it is not working on hover. Can you please look into the code and guide me a little. Thank you.

2020-10-23 19:14 UTC, shahednasser requested changes
So the problem is that you're using an image for the border. Instead, use the following:

```
    background-image: linear-gradient(#000, #000),linear-gradient( 115deg, #4fcf70, #fad648, #a767e5, #12bcfe, #44ce7b );
    background-origin: padding-box, border-box;
    background-repeat: no-repeat;
    border: 5px solid transparent;
    background-position: 0 0, 0% 50%;
    background-size: 100% 100%, 200% 200%;
```

And make the changes as requested below.
If you wanna play around with the animation and change it that's fine too.

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +  border: 5px solid;
Remove this

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +  border-image-slice: 1;
Remove this

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +  border-image-source: linear-gradient(
Remove this

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +    animation: colorwave 1.6s infinite;
add ease

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +    border-image-source: linear-gradient(
change this to 
```
background-position: 0 0, 0% 50%;
```

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +  25% {
Remove this

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +    border-image-source: linear-gradient(
Change this to 
```
    background-position: 0 0, 100% 50%;
```

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +  75% {
Remove this

2020-10-23 19:14 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +    border-image-source: linear-gradient(
Change this to 
```
background-position: 0 0, 0 50%;
```

2020-10-24 04:59 UTC, Soumi150 commented
Thank you very much.

2020-10-24 09:11 UTC, shahednasser requested changes
Looks good but in the animation you added the 0% and 50% but not the 100% so please fix that

2020-10-24 09:11 UTC, shahednasser commented on src/components/special/_rainbow-border.less
> +    animation: colorwave 1.6s ease infinite;
I think it would look better if it was slower so maybe change it to 3.6s

2020-10-26 12:04 UTC, merged

2020-10-26 12:04 UTC, shahednasser commented
Great work thank you!

@all-contributors please add @Soumi150 for code