New branch: made changes to _Western.less and incorporated under special instead of animated category
sButtons/sbuttons pull request #923
Opened 2020-10-23 21:27 UTC by laurachristensen1214

Issue:

2020-10-24 09:01 UTC, shahednasser requested changes
Thank you for your work @laurachristensen1214 but I can't see how the button looks like because you still need to run `npm run compile` then commit the changes.

Also, Please remove the file changes in `.vs/VSWorkspaceState.json` and `.vs/slnx.sqlite` as they are not necessary

2020-10-29 23:21 UTC, laurachristensen1214 commented
Hi @shahednasser I have resynced and compiled and made some changes to mine after looking at others'.

2020-10-30 11:17 UTC, shahednasser requested changes
Thank you for your work @laurachristensen1214 but I have some comments below. Can you please also remove all the changes in `.vs/slnx.sqlite` and `.vs/VSWorkspaceState.json` and `package-lock.json` and `package.json`? It makes the PR messy.

I realize that hacktoberfest is coming to an end soon and so I'll be adding `hacktoberfest-accepted` to your PR to make sure it's accepted even if it's not merged in time.

2020-10-30 11:17 UTC, shahednasser commented on CONTRIBUTING.md
> +  * [Button Ideas](#button-ideas)ru
remove this change

2020-10-30 11:17 UTC, shahednasser commented on src/components/special/_western.less
> +  &-denim {
Change this to `&.denim`

2020-10-30 11:17 UTC, shahednasser commented on src/components/special/_western.less
> +  &-choco {
Change this to &.choco

2020-10-30 11:17 UTC, shahednasser commented on src/components/special/_western.less
> +  &-charcoal {
Change this to &.charcoal

2020-10-30 11:17 UTC, shahednasser commented on src/components/special/_western.less
> +  &-sand {
Change this to &.sand

2020-10-30 11:17 UTC, shahednasser commented on src/_variables.less
> +@choco: #59452b;
Please rename all your variables to start with western (for example `@westernChoco`) that makes it easier to maintain later on.

2020-10-30 20:12 UTC, laurachristensen1214 commented
I have made changes and checked into new-branch. Sorry my repo seems to be such a mess! I'm trying to straighten it out a bit so it's not so confusing. And thank you for adding the accepted tag. 👍

2020-10-30 20:28 UTC, shahednasser requested changes
Ok now I can see the buttons, can you please make the borders more inside the button? What I mean by that is maybe you can make use of the `:before` or `:after` instead of applying the border directly to the button as it will make it look better.

Also please remove the changes in the files I've mentioned before

2020-11-09 11:09 UTC, shahednasser commented
Hi @laurachristensen1214 are you still working on this?

2020-11-17 00:12 UTC, closed without merging