changes
sButtons/sbuttons pull request #950
Opened 2020-10-26 07:13 UTC by adrsh79086

Issue:

2020-10-26 15:08 UTC, dsnehasish74 requested changes
Thank you for your work but can you please add this button in alphabetical order

2020-10-26 16:09 UTC, adrsh79086 commented
> Thank you for your work but can you please add this button in alphabetical order

okey i will do

2020-10-26 19:19 UTC, shahednasser requested changes
Please change the animation to happen on hover instead.

2020-10-26 19:19 UTC, shahednasser commented on assets/js/buttons-examples.js
> +        {
As @dsnehasish74 said please place it in the correct alphabetical order. Also, capitalize the first letter in the label

2020-10-26 19:26 UTC, glebkema commented
One more thanks for your PR! 

Please start your include less file with an underscore: `_ vibrate.less`. This helps Gulp distinguish the include files from the main file.

2020-10-26 19:28 UTC, shahednasser commented
Also as @glebkema pointed out, please rename the `vibrate.less` to `_vibrate.less` and change the import as well.

2020-10-26 19:29 UTC, glebkema commented on src/components/_animated.less
> +@import "animated/vibrate.less";
One more thanks for your PR!

Please start your include less file with an underscore: _vibrate.less. It helps Gulp distinguish the include files from the main file.

2020-10-28 09:44 UTC, dsnehasish74 reviewed
And please make the file name _vibrate.less instead of _Vibrate.less

2020-10-28 09:44 UTC, dsnehasish74 commented on assets/js/buttons-examples.js
> +          type: "Vibrate",
please make the first letter of the type small .

2020-10-29 12:10 UTC, closed without merging