White Space on border sides problem solved
sButtons/sbuttons pull request #970
Opened 2020-10-27 14:07 UTC by divyanshutewari17

Issue:

2020-10-27 14:18 UTC, dsnehasish74 reviewed
Thank you great work . 
but my suggestion is can you make this fill process little smooth ? then it will be great

2020-10-27 15:20 UTC, divyanshutewari17 commented
What type of change in filling you want can you please elaborate?

2020-10-28 07:15 UTC, dsnehasish74 commented
Suddenly removing border on hover is looking little odd for me I guess . Can you please put that border as it is or remove that border after the color filled completely . It is my suggestion . Fell free to share your opinion.

2020-10-28 14:44 UTC, divyanshutewari17 commented
@dsnehasish74 I have changed that glitch button size is not changing when being hovered

2020-10-28 16:26 UTC, dsnehasish74 requested changes
It looks good . it solved the problem for basic and rounded button but for block button case the block buttons converted in to the basic button when hover on that can you please  fix that

2020-10-28 17:08 UTC, divyanshutewari17 commented
@dsnehasish74 I missed that sorry, now I have resolved that too

2020-10-28 17:31 UTC, dsnehasish74 approved these changes
Yah !! Now it's looking cool . Thank you for your work @divyanshutewari17 , Great. @shahednasser  now you can merge this pr ,I think.

2020-10-28 17:37 UTC, divyanshutewari17 commented
@dsnehasish74 Thank You.

2020-10-28 19:13 UTC, shahednasser requested changes
Thank you for your work @divyanshutewari17 but it seems that you made changes to `dist/sbuttons.css` directly? Please reflect the changes in the less files in the `src` directory and then run `npm run compile` and commit the changes. Don't manually change the `dist/sbuttons.css` file.

2020-10-29 02:43 UTC, divyanshutewari17 commented
@shahednasser change in .less file are not being reflected on the project

2020-10-29 03:00 UTC, divyanshutewari17 commented
@shahednasser I downloaded both the CSS files again and apply changes to the ".less" file. Now I guess its good to merge

2020-10-29 03:02 UTC, divyanshutewari17 commented on dist/sbuttons.css
> +  border: 0rem;
Changed

2020-10-29 11:58 UTC, shahednasser commented
As I am not seeing the problem on my end, please @dsnehasish74 confirm that the problem is resolved

2020-10-30 03:00 UTC, dsnehasish74 commented
It's working fine  great

2020-10-30 11:20 UTC, merged

2020-10-30 11:20 UTC, shahednasser commented
Great work thank you!

@all-contributors please add @divyanshutewari17 for code and bug